SET( CPACK_PACKAGE_NAME ${APP_NAME} )
SET( CPACK_PACKAGE_VENDOR ${VENDOR} )
SET( CPACK_PACKAGE_VERSION_MAJOR ${MAJOR_VERSION} )
SET( CPACK_PACKAGE_VERSION_MINOR ${MINOR_VERSION} )
SET( CPACK_PACKAGE_VERSION_PATCH ${PATCH_VERSION}${SOURCE_MODIFIED_STR} )
SET( CPACK_PACKAGE_DESCRIPTION ${APP_DESC} )
SET( CPACK_PACKAGE_HOMEPAGE_URL ${PRODUCT_HOMEPAGE} )
#SET( CPACK_PACKAGE_ICON ${CMAKE_SOURCE_DIR}/Ui/resources/logo.bmp )
#SET( CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/" )
#SET( CPACK_RESOURCE_FILE_README ${CMAKE_SOURCE_DIR}/README.txt )
SET( CPACK_MONOLITHIC_INSTALL ON )
SET( CPACK_PACKAGE_EXECUTABLES ${APP_NAME}-gui ${APP_NAME})
SET( CPACK_CREATE_DESKTOP_LINKS ${APP_NAME}-gui )
SET( CPACK_THREADS 2 )
    
#set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "
#    CreateShortCut \\\"$DESKTOP\\\\${APP_NAME}.lnk\\\" \\\"$INSTDIR\\\\${APP_NAME}-gui.exe\\\"
#")

#set(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "
#    Delete \\\"$DESKTOP\\\\${APP_NAME}.lnk\\\"
#")

IF(UNIX)
    SET(CPACK_GENERATOR STGZ TGZ)
ELSE()
    SET( CPACK_GENERATOR ZIP )
ENDIF()

SET( CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON )
SET( CPACK_NSIS_EXECUTABLES_DIRECTORY "." )

include( CPack )

